# Generated by Django 3.2.7 on 2021-12-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('player_skill', models.CharField(blank=True, max_length=100, null=True)),
                ('player_team', models.CharField(max_length=100)),
            ],
        ),
    ]
